# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
    v.vmx["ethernet0.virtualdev"] = "e1000e"
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "2"
  end
end
